apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-$CLOUDFLARE_DOMAIN
  namespace: $SECRET_NAMESPACE
spec:
  secretName: myapp-cert
  issuerRef:
    name: $CA_NAME
    kind: ClusterIssuer
  commonName: $CLOUDFLARE_DOMAIN
  dnsNames:
  - $CLOUDFLARE_DOMAIN