apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
  namespace: cert-manager
spec:
  acme:
    email: "$CLOUDFLARE_EMAIL"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http-private-key
    solvers:
    - dns01:
        cloudflare:
          email: "$CLOUDFLARE_EMAIL"
          apiTokenSecretRef:
            name: cloudflare-api-secret
            key: api-token
