# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-config
  namespace: cert-manager
data:
  # These values will be populated from .env file
  domain: "${DOMAIN}"
  email: "${EMAIL}"
  