# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml

# Include the appropriate overlay based on ConfigMap


configMapGenerator:
- name: cert-manager-config
  envs:
  - config.env
