# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- cert-manager.yaml

configMapGenerator:
- name: cert-manager-config
  envs:
  - config.env
