# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- configmap.yaml
- cert-manager.yaml

# kustomization.yaml
configMapGenerator:
- name: cert-manager-config
  namespace: cert-manager
  envs:
  - config.env
