# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- configmap.yaml
- cert-manager.yaml




# Configure variable references
vars:
- name: CERT_MANAGER_EMAIL
  objref:
    kind: ConfigMap
    name: cert-manager-config
    namespace: cert-manager
  fieldref:
    fieldpath: data.email
- name: CERT_MANAGER_DOMAIN
  objref:
    kind: ConfigMap
    name: cert-manager-config
    namespace: cert-manager
  fieldref:
    fieldpath: data.domain

# Configure ConfigMap generation from .env file
configMapGenerator:
- name: cert-manager-config
  namespace: cert-manager
  envs:
  - config.env