apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-cert
  namespace: mlflow
spec:
  secretName: mlflow-tls
  issuerRef:
    name: self-signature-issuer
    kind: ClusterIssuer
  dnsNames:
    - mlflow.local
   


