apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- letsencrypt-clusterissuer.yaml
- letsencrypt-certificate.yaml

replacements:
- source:
    kind: ConfigMap
    name: ssl-config
    fieldPath: data.EMAIL
  targets:
  - select:
      kind: ClusterIssuer
      name: letsencrypt-prod
    fieldPaths:
    - spec.acme.email

- source:
    kind: ConfigMap
    name: ssl-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Certificate
      name: letsencrypt-cert
    fieldPaths:
    - spec.dnsNames.0
