apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - metadata-writer
resources:
  - ml-pipeline-apiserver-deployment.yaml
  - ml-pipeline-apiserver-role.yaml
  - ml-pipeline-apiserver-rolebinding.yaml
  - ml-pipeline-apiserver-sa.yaml
  - ml-pipeline-apiserver-service.yaml
  - ml-pipeline-persistenceagent-deployment.yaml
  - ml-pipeline-persistenceagent-role.yaml
  - ml-pipeline-persistenceagent-rolebinding.yaml
  - ml-pipeline-persistenceagent-sa.yaml
  - ml-pipeline-scheduledworkflow-deployment.yaml
  - ml-pipeline-scheduledworkflow-role.yaml
  - ml-pipeline-scheduledworkflow-rolebinding.yaml
  - ml-pipeline-scheduledworkflow-sa.yaml
  - ml-pipeline-ui-deployment.yaml
  - ml-pipeline-ui-configmap.yaml
  - ml-pipeline-ui-role.yaml
  - ml-pipeline-ui-rolebinding.yaml
  - ml-pipeline-ui-sa.yaml
  - ml-pipeline-ui-service.yaml
  - ml-pipeline-viewer-crd-role.yaml
  - ml-pipeline-viewer-crd-rolebinding.yaml
  - ml-pipeline-viewer-crd-deployment.yaml
  - ml-pipeline-viewer-crd-sa.yaml
  - ml-pipeline-visualization-deployment.yaml
  - ml-pipeline-visualization-sa.yaml
  - ml-pipeline-visualization-service.yaml
  - pipeline-runner-role.yaml
  - pipeline-runner-rolebinding.yaml
  - pipeline-runner-sa.yaml
  - container-builder-sa.yaml
  - viewer-sa.yaml
  - kfp-launcher-configmap.yaml
  - ml-pipeline-ui-ingress.yaml
  - ml-pipeline-ui-virtual-service.yaml
images:
  - name: gcr.io/ml-pipeline/api-server
    newTag: 2.0.0-alpha.7
  - name: gcr.io/ml-pipeline/persistenceagent
    newTag: 2.0.0-alpha.7
  - name: gcr.io/ml-pipeline/scheduledworkflow
    newTag: 2.0.0-alpha.7
  - name: gcr.io/ml-pipeline/frontend
    newTag: 2.0.0-alpha.7
  - name: gcr.io/ml-pipeline/viewer-crd-controller
    newTag: 2.0.0-alpha.7
  - name: gcr.io/ml-pipeline/visualization-server
    newTag: 2.0.0-alpha.7

configMapGenerator:
  - name: mlpipepline-configmap
    envs:
      - config.env
    behavior: replace

replacements:
  - source:
      kind: ConfigMap
      name: mlpipepline-configmap
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: ml-pipeline-ui-ingress
        fieldPaths:
          - spec.rules.0.host
      - select:
          kind: VirtualService
          name: ml-pipeline-ui-virtual-service
        fieldPaths:
          - spec.hosts.0
      - select:
          kind: Service
          name: ml-pipeline-ui-ingress
        fieldPaths:
          - spec.tls.0.hosts.0
