apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-configmap
data:
   DOMAIN: ${DOMAIN}
   viewer-pod-template.json:  |-
    {
        "spec": {
            "serviceAccountName": "kubeflow-pipelines-viewer"
        }
    }
