apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mlflow-namespace.yaml
  - mlflow-deployment.yaml
  - mlflow-service.yaml
  - mlflow-sa.yaml
  - mlflow-virtualservice.yaml
  - mlflow-ingress.yaml

configMapGenerator:
  - name: mlflow-configmap
    envs:
      - config.env
    behavior: replace

secretGenerator:
  - name: mlflow-secret
    literals:
      - DB_PASSWORD=KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og

replacements:
  - source:
      kind: ConfigMap
      name: mlflow-configmap
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: mlflow-ingress
        fieldPaths:
          - spec.rules.0.host