apiVersion: kustomize.config.k8s.io/v1alpha1
kind: PatchTransformer
metadata:
  name: patch-ca-selector
patch: |
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  metadata:
    name: patch-overlay
  resources:
  - ../overlays/$(SSL_PROVIDER)
target:
  kind: Kustomization
  name: .*
vars:
- name: SSL_PROVIDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cert-manager-ca-config
  fieldref:
    fieldpath: data.SSL_PROVIDER
