# zerossl/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- zerossl-clusterissuer.yaml
- zerossl-certificate.yaml

secretGenerator:
- name: zerossl-api-secret
  literals:
  - api-key=${ZEROSSL_API_TOKEN}

configMapGenerator:
- name: cert-manager-config
  envs:
  - ../base/config.env # or the correct relative path
replacements:
- source:
    kind: ConfigMap
    name: ssl-config
    fieldPath: data.EMAIL
  targets:
  - select:
      kind: ClusterIssuer
      name: zerossl-prod
    fieldPaths:
    - spec.acme.email

- source:
    kind: ConfigMap
    name: ssl-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Certificate
      name: zerossl-cert
    fieldPaths:
    - spec.dnsNames.0
