apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
  namespace: cert-manager
spec:
  acme:
    # ZeroSSL ACME server
    server: https://acme.zerossl.com/v2/DV90
    email: your@email.com # This will be replaced by the value from EMAIL in config.env
    privateKeySecretRef:
      name: zerossl-prod
    externalAccountBinding:
      keyID: YOUR_EAB_KID # This will be replaced by the value from ZEROSSL_ACCESS_KEY_ID in config.env
      keySecretRef:
        name: zerossl-eab-secret # Must match the name in secretGenerator
        key: secret # Key within the secret that contains the HMAC value
      keyAlgorithm: HS256
    solvers:
    - http01:
        ingress:
          class: nginx
