apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
  namespace: cert-manager
spec:
  acme:
    # ZeroSSL ACME server
    server: https://acme.zerossl.com/v2/DV90
    email: your@email.com
    privateKeySecretRef:
      name: zerossl-prod
    externalAccountBinding:
      keyID: YOUR_EAB_KID
      keySecretRef:
        name: zerossl-api-secret
        key: eab_hmac_key
      keyAlgorithm: HS256
    solvers:
    - http01:
        ingress:
          class: nginx
