# zerossl/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zerossl-cert
  namespace: cert-manager
spec:
  secretName: zerossl-tls
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
  dnsNames:
  - ${CERT_MANAGER_DOMAIN}
  