apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: mlflow
data:
  MINIO_BROWSER: "on"
  MINIO_ACCESS_KEY: "your-access-key"
  MINIO_SECRET_KEY: "your-secret-key"
  MINIO_BROWSER_REDIRECT_URL: "https://mlops.local/minio/"
