# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- cert-manager.yaml
- letsclusterissuer.yaml
- letscertificate.yaml

configMapGenerator:
- name: cert-manager-config
  envs:
  - config.env # or the correct relative path 

replacements:
- source:
    kind: ConfigMap
    name: cert-manager-config
    fieldPath: data.EMAIL
  targets:
  - select:
      kind: ClusterIssuer
      name: letsencrypt
    fieldPaths:
    - spec.acme.email

- source:
    kind: ConfigMap
    name: cert-manager-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Certificate
      name: myapp-cert
    fieldPaths:
    - spec.dnsNames.0
