# patches/select-ca.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Patch
metadata:
  name: ca-selector
patches:
- target:
    kind: ""
  patch: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
    # Always include configmap
    - configmap.yaml
    # Conditional includes based on CA_PROVIDER value
    $patch: $CA_PROVIDER == "letsencrypt" || $CA_PROVIDER == "both" ? append : noop
    - letsencrypt-clusterissuer.yaml
    - letsencrypt-certificate.yaml
    $patch: $CA_PROVIDER == "zerossl" || $CA_PROVIDER == "both" ? append : noop
    - zerossl-clusterissuer.yaml
    - zerossl-certificate.yaml