apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-root-url-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = mlops.local
    root_url = %(protocol)s://%(domain)s/grafana
    serve_from_sub_path = true

    [paths]
    root_path = /grafana

    [security]
    # Default login credentials (for development/testing only)
    disable_initial_admin_creation = false
    admin_user = admin
    admin_password = admin
    cookie_secure = true
    cookie_samesite = lax
