apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-root-url-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = mlops.local
    root_url = %(protocol)s://%(domain)s/grafana
    serve_from_sub_path = true
