namespace: monitoring

resources:
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-datasource-config.yaml
- grafana-pvc.yaml
- dashboards-config-map.yaml
- dashboards-json-config-map.yaml
- grafana-ingress.yaml
- grafana-virtualservice.yaml

replacements:
- source:
    kind: ConfigMap
    name: ssl-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Ingress
      name: grafana-ingress
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
  - select:
      kind: VirtualService
      name: grafana-virtual-service
    fieldPaths:
    - spec.http.0.route.0.headers.response.set.Access-Control-Allow-Origin
    - spec.http.0.corsPolicy.allowOrigins.0.exact
