namespace: monitoring

resources:
- prometheus-cluster-role-binding.yaml
- prometheus-cluster-role.yaml
- prometheus-config-map.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-pvc.yaml
- prometheus-ingress.yaml
- prometheus-virtualservice.yaml

configMapGenerator:
  - name: prometheus-configmap
    envs:
      - config.env
    behavior: replace

secretGenerator:
  - name: prometheus-secret
    literals:
      - DB_PASSWORD=KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og

replacements:
  - source:
      kind: ConfigMap
      name: prometheus-configmap
      fieldPath: data.DOMAIN
    targets:
      - select:
          kind: Ingress
          name: prometheus-ingress
        fieldPaths:
          - spec.rules.0.host
      - select:
          kind: VirtualService
          name: prometheus-virtualservice
        fieldPaths:
          - spec.hosts.0
      - select:
          kind: Service
          name: prometheus-ingress
        fieldPaths:
          - spec.tls.0.hosts.0