namespace: monitoring

resources:
- prometheus-cluster-role-binding.yaml
- prometheus-cluster-role.yaml
- prometheus-config-map.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-pvc.yaml
- prometheus-ingress.yaml
- prometheus-virtualservice.yaml

configMapGenerator:
  - name: prometheus-configmap
    envs:
      - config.env
    behavior: replace

replacements:
  - source:
      kind: ConfigMap
      name: prometheus-configmap
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: prometheus-ingress
        fieldPaths:
          - spec.rules.0.host